// Generated by Dagger (https://dagger.dev).
package com.weemusic.android.shared.util;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class NetworkConnection_Factory implements Factory<NetworkConnection> {
  private final Provider<Context> contextProvider;

  public NetworkConnection_Factory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public NetworkConnection get() {
    return newInstance(contextProvider.get());
  }

  public static NetworkConnection_Factory create(Provider<Context> contextProvider) {
    return new NetworkConnection_Factory(contextProvider);
  }

  public static NetworkConnection newInstance(Context context) {
    return new NetworkConnection(context);
  }
}
